import { HomePageFaqItem } from "../../HomePageFaqItem";
import s from "./HomePageFaq.module.scss";

const questions = [
  {
    question: "What is Beetroot Finance?",
    answer:
      "Beetroot Finance is an automated yield farming aggregator on TON blockchain. We enable users to earn competitive yields on their stablecoins through an automated process. By utilizing a single yield-bearing token, we streamline investments and maximize yield opportunities within  the TON DeFi ecosystem.",
  },
  {
    question: "How is the yield earned?",
    answer:
      "The yield is generated by automated optimization algorithms that intelligently route stablecoin lending, constantly rebalancing funds to secure the highest rates.",
  },
  {
    question: "How does the yield getpaid to me?",
    answer:
      "Yield is automatically accrued and reflects in the value of the ROOT token held in your wallet. When you redeem your ROOT token, you receive back the initial stablecoin you deposited and the yield accrued.",
  },
  {
    question: "When can I withdraw my stablecoins?",
    answer:
      "You can withdraw at any time without any lockup period. The process is designed to be straightforward and flexible to meet users' needs.",
  },
  {
    question: "How do I get ROOT?",
    answer:
      "You can obtain ROOT by minting using your USDT directly in our Telegram Mini App.",
  },
  {
    question: "What risks should I know about?",
    answer:
      "There are always risks when interacting with DeFi. The underlying stablecoins can depeg. A significant exploit can occur to Beetroot Finance or the pools that Beetroot Finance operates within.",
  },
  {
    question: "How do you manage risk?",
    answer:
      "We employ risk management strategies, including diversification across different yield opportunities and continuous monitoring of the platforms' performance to mitigate potential risks.",
  },
  {
    question: "Have you been audited?",
    answer: "Not yet, but we will publicly announce once we get audited.",
  },
];

export const HomePageFaq = () => {
  return (
    <div className={s.wrapper}>
      <div className={s.title}>FAQ - Frequently Asked Questions</div>
      <div className={s.items}>
        {questions.map((item, i) => (
          <HomePageFaqItem {...item} key={i} />
        ))}
      </div>
    </div>
  );
};
